version: 2

executor:
  node:
    parameters:
      node:
        type: string
    docker:
      - image: circleci/node:<< parameters.node >>

jobs:
  checkout:
    working_directory: ~/repo
    executor: node
    steps:
      - checkout

  - restore_cache:
    executor: node
    parameters:
      node:
        type: string
    keys:
      - v1-dependencies-<< parameters.node >>-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-<< parameters.node >>-

  verify_build:
    working_directory: ~/repo
    executor: node
    steps:
      - yarn install
      - yarn build
      - yarn lint
      - yarn check-formatting
      - yarn test

  - save_cache:
    executor: node
    parameters:
      node:
        type: string
    paths:
      - node_modules
    keys:
      - v1-dependencies-<< parameters.node >>-{{ checksum "package.json" }}

workflows:
  node-v810:
    jobs:
      checkout:
        - node: "8.10"
      restore_cache:
        - node: "8.10"
      verify_build:
        - node: "8.10"
      save_cache:
        - node: "8.10"
  node-v1015:
    jobs:
      checkout:
        - node: "10.15"
      restore_cache:
        - node: "10.15"
      verify_build:
        - node: "10.15"
      save_cache:
        - node: "10.15"
