version: 2.1

jobs:
  verify_build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:<< parameters.node >>
    parameters:
      node:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-<< parameters.node >>-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-<< parameters.node >>-
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn check-formatting
      - run: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.node >>-{{ checksum "package.json" }}

workflows:
  node-v810:
    jobs:
      - verify_build:
          node: "8.10"

  node-v1015:
    jobs:
      - verify_build:
          node: "10.15"
